apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: config-service
    namespace: argocd
spec:
    source:
        targetRevision: HEAD
        helm:
            values: |
                image:
                    tag: latest
    destination:
        namespace: production
