apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: website
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        path: src/main/helm
        repoURL: https://github.com/bootifulmicropizza/v2_website.git
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
          - CreateNamespace=true
